# Generated by Django 6.0.2 on 2026-04-14 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('anneeSecurite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Phase d'archivage",
                'verbose_name_plural': "Phases d'archivage",
            },
        ),
        migrations.CreateModel(
            name='Armoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('code_barres', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Armoire',
                'verbose_name_plural': 'Armoires',
                'ordering': ['salle', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('ville', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('idBordereau', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('pdf_generé', models.FileField(upload_to='bordereaux/')),
            ],
            options={
                'verbose_name': 'Bordereau',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('isDefault', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveCourant',
            fields=[
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='archives.phasearchive')),
                ('duree', models.IntegerField(default=3)),
                ('directionResponsable', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveDefinitive',
            fields=[
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='archives.phasearchive')),
                ('dispositionFinale', models.CharField(max_length=200)),
                ('dateDisposition', models.DateField()),
                ('anneeSecurite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveIntermediaire',
            fields=[
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='archives.phasearchive')),
                ('duree', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Boitier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idboit', models.CharField(max_length=50, unique=True)),
                ('code_barre', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('capacite', models.IntegerField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('PLEIN', 'Plein'), ('ARCHIVE', 'Archivé'), ('EN_TRANSFERT', 'En transfert'), ('EN_PREPARATION', 'En préparation')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('armoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boitiers', to='archives.armoire')),
            ],
            options={
                'verbose_name': 'Boîtier',
                'ordering': ['idboit'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDoc', models.CharField(max_length=50, unique=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=500)),
                ('date_creation', models.DateField()),
                ('niv_confidentialite', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNE', 'Interne'), ('CONFIDENTIEL', 'Confidentiel'), ('SECRET', 'Secret')], default='INTERNE', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('RAPPORT', 'Rapport'), ('COURRIER', 'Courrier'), ('FORMULAIRE', 'Formulaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('taille_fichier', models.BigIntegerField(blank=True, null=True)),
                ('hash_fichier', models.CharField(blank=True, max_length=64)),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('historique_versions', models.JSONField(blank=True, default=list)),
                ('historique_consultations', models.JSONField(blank=True, default=list)),
                ('phase_archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='archives.phasearchive')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-date_creation', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=200)),
                ('consultation', models.TextField()),
                ('poste', models.CharField(blank=True, max_length=100)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('reasonForRejection', models.TextField(blank=True)),
                ('approvedBy', models.CharField(blank=True, max_length=100)),
                ('rejectedBy', models.CharField(blank=True, max_length=100)),
                ('approvalDate', models.DateTimeField(blank=True, null=True)),
                ('rejectionDate', models.DateTimeField(blank=True, null=True)),
                ('allitemsReturned', models.BooleanField(default=False)),
                ('createdBy', models.CharField(blank=True, max_length=100)),
                ('modifiedBy', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='archives.document')),
            ],
            options={
                'verbose_name': 'Consultation',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('idDossier', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_creation', models.DateField()),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('phaseType', models.CharField(default='COURANTE', max_length=50)),
                ('dureeCourant', models.IntegerField(default=3)),
                ('dureeIntermediaire', models.IntegerField(default=10)),
                ('anneeSecurite', models.IntegerField(blank=True, null=True)),
                ('boitier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='archives.boitier')),
                ('phaseArchive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.phasearchive')),
            ],
            options={
                'verbose_name': 'Dossier',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='archives.dossier'),
        ),
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('code_barres', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('armoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etageres', to='archives.armoire')),
            ],
            options={
                'verbose_name': 'Étagère',
                'verbose_name_plural': 'Étagères',
                'ordering': ['armoire', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='boitier',
            name='etagere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boitiers', to='archives.etagere'),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('etage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='archives.batiment')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['batiment', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='armoire',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armoires', to='archives.salle'),
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bordereauxReference', models.CharField(blank=True, max_length=100)),
                ('typeTransfer', models.CharField(default='INTERNE', max_length=50)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.document')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.dossier')),
            ],
            options={
                'verbose_name': 'Transfert',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['idDoc'], name='archives_do_idDoc_06fa28_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['reference'], name='archives_do_referen_d9d0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['phase_archive'], name='archives_do_phase_a_5257db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etagere',
            unique_together={('armoire', 'numero')},
        ),
        migrations.AddIndex(
            model_name='boitier',
            index=models.Index(fields=['idboit'], name='archives_bo_idboit_7169a7_idx'),
        ),
        migrations.AddIndex(
            model_name='boitier',
            index=models.Index(fields=['code_barre'], name='archives_bo_code_ba_90e3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='boitier',
            index=models.Index(fields=['statut'], name='archives_bo_statut_cc25a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together={('batiment', 'nom')},
        ),
    ]
