# Generated by Django 6.0.2 on 2026-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='anneeSecurite',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='description',
        ),
        migrations.AddField(
            model_name='dossier',
            name='dureeDefinitive',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='dossier',
            name='nomDos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
