# Generated by Django 6.0.2 on 2026-04-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_remove_dossier_anneesecurite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['nom'],
            },
        ),
    ]
