# Generated by Django 6.0.2 on 2026-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_remove_dossier_anneesecurite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armoire',
            name='date_installation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armoire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armoire',
            name='type_armoire',
            field=models.CharField(default='METAL', max_length=50),
        ),
        migrations.AddField(
            model_name='etagere',
            name='capacite_max_boites',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='etagere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etagere',
            name='occupation_actuelle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salle',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
