# Generated by Django 6.0.2 on 2026-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_armoire_date_installation_armoire_description_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='armoire',
                    name='date_installation',
                ),
                migrations.RemoveField(
                    model_name='armoire',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='armoire',
                    name='type_armoire',
                ),
                migrations.RemoveField(
                    model_name='etagere',
                    name='capacite_max_boites',
                ),
                migrations.RemoveField(
                    model_name='etagere',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='etagere',
                    name='occupation_actuelle',
                ),
            ],
        ),
        migrations.AddField(
            model_name='salle',
            name='type_salle',
            field=models.CharField(default='ARCHIVE', max_length=50),
        ),
    ]
