# Generated by Django 6.0.2 on 2026-04-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_direction'),
        ('calendrier', '0004_recreate_calendrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='calendrier.calendrier', db_constraint=False),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['fk'], name='archives_do_fk_id_d8646a_idx'),
        ),
    ]
