# Generated by Django 6.0.2 on 2026-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_role_options_remove_armoire_hauteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
