# Generated by Django 6.0.2 on 2026-04-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_document_fk_document_archives_do_fk_id_d8646a_idx'),
        ('calendrier', '0004_recreate_calendrier'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=lambda apps, schema_editor: _reconcile_calendrier_db(schema_editor),
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='document',
                    old_name='fk',
                    new_name='calendrier',
                ),
                migrations.AddIndex(
                    model_name='document',
                    index=models.Index(fields=['calendrier'], name='archives_do_calendr_a766e5_idx'),
                ),
            ],
        ),
    ]


def _reconcile_calendrier_db(schema_editor):
    """Reconcile possible duplicate/partial columns left by previous failed migration.

    - If both `fk_id` and `calendrier_id` exist: copy values where needed, drop old index and drop `fk_id`.
    - If only `fk_id` exists: rename it to `calendrier_id` preserving type/null/default.
    - Ensure an index on `calendrier_id` exists.
    """
    conn = schema_editor.connection
    table = 'archives_document'
    cursor = conn.cursor()
    try:
        def col_exists(col_name):
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
                [table, col_name],
            )
            return cursor.fetchone()[0] > 0

        has_cal = col_exists('calendrier_id')
        has_fk = col_exists('fk_id')

        if has_cal and has_fk:
            # copy values from fk -> calendrier where calendrier is null
            cursor.execute(f"UPDATE {table} SET calendrier_id = fk_id WHERE calendrier_id IS NULL AND fk_id IS NOT NULL")
            # drop old fk index if exists
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s",
                [table, 'archives_do_fk_id_d8646a_idx'],
            )
            if cursor.fetchone()[0] > 0:
                try:
                    cursor.execute(f"DROP INDEX archives_do_fk_id_d8646a_idx ON {table}")
                except Exception:
                    pass
            # drop the old column
            cursor.execute(f"ALTER TABLE {table} DROP COLUMN fk_id")

        elif has_fk and not has_cal:
            # rename fk_id -> calendrier_id preserving type, nullability and default
            cursor.execute(
                "SELECT COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
                [table, 'fk_id'],
            )
            row = cursor.fetchone()
            if row:
                col_type, is_nullable, default = row
                null_sql = 'NULL' if is_nullable == 'YES' else 'NOT NULL'
                default_sql = f" DEFAULT '{str(default).replace("'", "''")}'" if default is not None else ''
                sql = f"ALTER TABLE {table} CHANGE COLUMN fk_id calendrier_id {col_type} {null_sql}{default_sql}"
                cursor.execute(sql)

        # Ensure calendrier index exists
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s",
            [table, 'archives_do_calendr_a766e5_idx'],
        )
        if cursor.fetchone()[0] == 0 and col_exists('calendrier_id'):
            try:
                cursor.execute(f"CREATE INDEX archives_do_calendr_a766e5_idx ON {table} (calendrier_id)")
            except Exception:
                pass
    finally:
        try:
            cursor.close()
        except Exception:
            pass
