# Generated by Django 6.0.2 on 2026-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_armoire_date_installation_armoire_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
