# Generated by Django 6.0.2 on 2026-03-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_batiment_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='type_salle',
            field=models.CharField(choices=[('ARCHIVE', "Salle d'archive")], default='ARCHIVE', max_length=20),
        ),
    ]
