# Generated by Django 6.0.2 on 2026-04-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_alter_salle_type_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armoire',
            name='type_armoire',
        ),
    ]
