# Generated by Django 6.0.2 on 2026-04-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_boitier_description'),
        ('archives', '0011_remove_document_archives_do_fk_id_d8646a_idx_and_more'),
    ]

    operations = [
    ]
