# Generated by Django 6.0.2 on 2026-04-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0012_merge_20260427_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='phase_archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='archives.phasearchive'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(blank=True, choices=[('CONTRAT', 'Contrat'), ('FACTURE', 'Facture'), ('RAPPORT', 'Rapport'), ('COURRIER', 'Courrier'), ('FORMULAIRE', 'Formulaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, null=True),
        ),
    ]
