# Generated by Django 6.0.2 on 2026-04-28 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0013_alter_document_phase_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_creation',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
