# Generated by Django 6.0.2 on 2026-04-28 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0014_make_date_creation_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_creation',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
