# Generated by Django 6.0.2 on 2026-04-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0015_make_dossier_date_creation_optional'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE archives_document MODIFY COLUMN action_finale VARCHAR(255) DEFAULT '' NULL;",
            reverse_sql="ALTER TABLE archives_document MODIFY COLUMN action_finale VARCHAR(255);",
        ),
    ]
