# Generated by Django 6.0.2 on 2026-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0022_backfill_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
