# Generated by Django 6.0.2 on 2026-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0023_document_action_finale_dossier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boitier',
            name='code_barre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
