# Generated by Django 6.0.2 on 2026-05-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0024_document_action_finale_alter_boitier_code_barre'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
