# Generated by Django 6.0.2 on 2026-04-18 11:44

from django.db import migrations


def migrate_direction_codes(apps, schema_editor):
    Calendrier = apps.get_model('calendrier', 'Calendrier')
    Direction = apps.get_model('archives', 'Direction')
    for cal in Calendrier.objects.all():
        code = getattr(cal, 'direction_id', None)
        if code:
            direction = Direction.objects.filter(code=code).first()
            if direction:
                cal.direction_fk = direction
                cal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_calendrier_direction_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_direction_codes, reverse_code=migrations.RunPython.noop),
    ]
