"""Drop and recreate Calendrier table with `direction` FK.

Generated by assistant.
"""
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0003_migrate_direction_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendrier',
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_dossier', models.BooleanField(default=False)),
                ('exemplaire_type', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendriers', to='archives.direction')),
                ('sous_direction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('conservation_active_period', models.IntegerField(blank=True, null=True)),
                ('conservation_semi_active_period', models.IntegerField(blank=True, null=True)),
                ('sort_final_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_final_comment', models.TextField(blank=True, null=True)),
                ('sort_final_security_years', models.IntegerField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('validation_archive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='calendrier.calendrier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
